config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'home#index'
    
    namespace :manage do
      get 'add_event' => 'events#add_event'
    end
    
    get 'resources' => 'resources#index'
    get 'events' => 'events#index'
  end
  
  mount RailsAdmin::Engine => '/admin/manage', as: 'rails_admin'
  
  resources :events
  
  get 'reimbursement_request' => 'reimbursements#reimbursement_request'
  get 'reimbursement_already_exists' => 'reimbursements#reimbursement_already_exists'
  

end

app/models/attended_event.rb
class AttendedEvent < ActiveRecord::Base
  belongs_to :event
  belongs_to :member
  
  before_destroy { |record| member.remove_volunteer_hours(event.volunteer_hours) }
end

app/models/club_fund_activity.rb
class ClubFundActivity < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :event_type
  
  has_many :attended_events, dependent: :destroy
  has_many :reimbursements, dependent: :destroy
  has_many :attendees, through: :attended_events, source: :member
end

app/models/event_type.rb
class EventType < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :attended_events
  has_many :events_attended, through: :attended_events, source: :event
  
  after_initialize do
    if new_record?
      self.volunteer_hours ||= 0
    end
  end
  
  def add_volunteer_hours(hours)
    current_volunteer_hours = self.volunteer_hours || 0
    update_attributes(volunteer_hours: current_volunteer_hours + hours)
  end
  
  def remove_volunteer_hours(hours)
    current_volunteer_hours = self.volunteer_hours || 0
    new_hours_count = [0, current_volunteer_hours - hours].max
    update_attributes(volunteer_hours: new_hours_count)
  end
  
  def qualifies_for_uniform?
    return self.volunteer_hours > 15
  end
end

app/models/reimbursement.rb
class Reimbursement < ActiveRecord::Base
  belongs_to :event
  belongs_to :member
end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/controllers/admin/events_controller.rb
module Admin  
  class EventsController < ApplicationController
    skip_before_action :protect_from_forgery
    protect_from_forgery with: :null_session
    
    before_action :set_event, only: [:update, :destroy]
  
    # GET /events
    # GET /events.json
    def index
      @events = Event.all
    end
  
    # POST /events
    # POST /events.json
    def create
      @event = Creators::Event.new.create_from_post(attendees_param, event_params)
      
      respond_to do |format|
        if @event.save
          format.html { redirect_to '/admin/manage/event', notice: 'Event was successfully created.' }
          format.json { render :show, status: :created, location: @event }
        else
          format.html { render :new }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /events/1
    # PATCH/PUT /events/1.json
    def update
      respond_to do |format|
        if @event.update(event_params)
          format.html { redirect_to @event, notice: 'Event was successfully updated.' }
          format.json { render :show, status: :ok, location: @event }
        else
          format.html { render :edit }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /events/1
    # DELETE /events/1.json
    def destroy
      @event.destroy
      respond_to do |format|
        format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_event
        @event = Event.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def event_params
        params.require(:event).permit(
          :name,
          :date,
          :event_summary,
          :comments,
          :volunteer_hours,
          :driving_distance,
          :start_time,
          :end_time,
          :event_type_id
          )
      end
      
      def attendees_param
        params.require(:attendees).map do |p|
          ActionController::Parameters.new(p.to_hash).permit(:id, :drove)
        end
      end
  end
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < ApplicationController
    def index
    end
  end
end

app/controllers/admin/resources_controller.rb
module Admin
  class ResourcesController < ApplicationController
    def index
      @resources = Resource.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/custom_admin/events_controller.rb
module CustomAdmin  
  class EventsController < ApplicationController
    layout 'admin'
    
    def add_event
      @event_types = EventType.all
      @members = Member.all
      
      event_types = []
      EventType.all.each do |event_type|
        event_type_data = {
          id: event_type.id,
          name: event_type.name,
          volunteer_hours: event_type.volunteer_hours,
          driving_distance: event_type.driving_distance,
          start_time_hour: event_type.try(:start_time).try(:hour),
          start_time_minutes: event_type.try(:start_time).try(:min),
          end_time_hour: event_type.try(:end_time).try(:hour),
          end_time_minutes: event_type.try(:end_time).try(:min)
        }
        
        event_types.push(event_type_data)
      end
      
      @event_types = event_types
    end
  end
end

app/controllers/reimbursements_controller.rb
class ReimbursementsController < ApplicationController
  before_action :check_for_existing_reimbursement, only: [:reimbursement_request]
  
  def reimbursement_request
    member = Member.find(reimbursement_params[:member_id])
    event = Event.find(reimbursement_params[:event_id])
    options = {
      claimed: reimbursement_params[:claimed] == "true",
      amount: reimbursement_params[:amount]
    }
    
    Creators::Reimbursement.new.create(member, event, options)
    
    render "confirmation"
  end
  
  def reimbursement_already_exists
  end
  
  private
    def reimbursement_params
      params.require(:reimbursement).permit(
        :member_id,
        :event_id,
        :claimed,
        :amount
      )
    end
    
    def check_for_existing_reimbursement
      reimbursement_exists = Reimbursement.find_by(
        member_id: reimbursement_params[:member_id],
        event_id: reimbursement_params[:event_id]
      )
      
      if reimbursement_exists
        redirect_to reimbursement_already_exists_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reimbursements_helper.rb
module ReimbursementsHelper
  def reimbursement_dollar_amount(num_miles)
    num_miles * 0.58
  end
end

app/views/admin/events/add_event.html.erb
<div class="page-header">
  <h1>Submit New Event</h1>
</div>

<%= react_component("NewEventPage", props: {authenticityToken: form_authenticity_token, members: @members, eventTypes: @event_types}, prerender: false) %>

app/views/admin/events/index.html.erb
<div id="site-home-page" class="page">
  <%= render "shared/site_header" %>
  
  <div class="page-content">
    <div id="navigation">
      <div class="navigation-panels">
        <div class="navigation-panel-container">
          <a href=<%= admin_events_path %>>
            <div class="navigation-panel-content">
              <div class="panel-icon">
                <i class="fab fa-elementor"></i>
              </div>
              <div class="panel-label">
                <span>Events</span>
              </div>
            </div>
          </a>
        </div>
        <div class="navigation-panel-container">
          <a href=<%= admin_resources_path %>>
            <div class="navigation-panel-content">
              <div class="panel-icon">
                <i class="fas fa-users"></i>
              </div>
              <div class="panel-label">
                <span>Members</span>
              </div>
            </div>
          </a>
        </div>
        <div class="navigation-panel-container">
          <a href=<%= admin_resources_path %>>
            <div class="navigation-panel-content">
              <div class="panel-icon">
                <i class="far fa-address-card"></i>
              </div>
              <div class="panel-label">
                <span>Officer</span>
              </div>
            </div>
          </a>
        </div>
        <div class="navigation-panel-container">
          <a href=<%= admin_resources_path %>>
            <div class="navigation-panel-content">
              <div class="panel-icon">
                <i class="fas fa-book"></i>
              </div>
              <div class="panel-label">
                <span>Resources</span>
              </div>
            </div>
          </a>
        </div>
        <div class="navigation-panel-container">
          <a href=<%= rails_admin_path %>>
            <div class="navigation-panel-content">
              <div class="panel-icon">
                <i class="fas fa-tools"></i>
              </div>
              <div class="panel-label">
                <span>Admin</span>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
    
    <div class="events-header-row">
      <h2>UPCOMING EVENTS</h2>
      <a href="" id="add-new-event-button">+</a>
    </div>
      
    <div id="upcoming-events-container">
      <div id="upcoming-events-list-container">
        <ul id="upcoming-events-list">
          <li class="upcoming-events-list-item">
            <div class="date-section">
              <div class="month">SEPT</div>
              <div class="number">9</div>
              <div class="day-of-week">WED</div>
            </div>
            <div class="details">
              <div class="event-name">Convalescent Home Visit</div>
              <div class="event-time">10:00 AM - 12:00 PM</div>
            </div>
          </li>
        </ul>
      </div>
    </div>
    
    <div class="events-header-row">
      <h2>RECENT EVENTS</h2>
    </div>
    
    <div id="upcoming-events-container">
      <div id="upcoming-events-list-container">
        <ul id="upcoming-events-list">
          <li class="upcoming-events-list-item">
            <div class="date-section">
              <div class="month">AUG</div>
              <div class="number">15</div>
              <div class="day-of-week">FRI</div>
            </div>
            <div class="details">
              <div class="event-name">Social Night</div>
              <div class="event-time">8:00 PM - 10:00 PM</div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/admin/events/manage_event.html.erb
<div class="page-header">
  <h1>Manage Event</h1>
</div>

<%= react_component(
  "ManageEventPage", 
  props: {
    authenticityToken: form_authenticity_token,
    event: @event,
    event_types: @event_types,
    members: @members
  }, 
  prerender: false) 
%>

app/views/admin/home/index.html.erb
<div id="site-home-page" class="page">
  <%= render "shared/site_header" %>
  
  <div class="page-content">
    <div id="navigation">
      <div class="navigation-panels">
        <div class="navigation-panel-container">
          <a href=<%= admin_resources_path %>>
            <div class="navigation-panel-content">
              <div class="panel-icon">
                <i class="fab fa-elementor"></i>
              </div>
              <div class="panel-label">
                <span>Events</span>
              </div>
            </div>
          </a>
        </div>
        <div class="navigation-panel-container">
          <a href=<%= admin_resources_path %>>
            <div class="navigation-panel-content">
              <div class="panel-icon">
                <i class="fas fa-users"></i>
              </div>
              <div class="panel-label">
                <span>Members</span>
              </div>
            </div>
          </a>
        </div>
        <div class="navigation-panel-container">
          <a href=<%= admin_resources_path %>>
            <div class="navigation-panel-content">
              <div class="panel-icon">
                <i class="far fa-address-card"></i>
              </div>
              <div class="panel-label">
                <span>Officer</span>
              </div>
            </div>
          </a>
        </div>
        <div class="navigation-panel-container">
          <a href=<%= admin_resources_path %>>
            <div class="navigation-panel-content">
              <div class="panel-icon">
                <i class="fas fa-book"></i>
              </div>
              <div class="panel-label">
                <span>Resources</span>
              </div>
            </div>
          </a>
        </div>
        <div class="navigation-panel-container">
          <a href=<%= rails_admin_path %>>
            <div class="navigation-panel-content">
              <div class="panel-icon">
                <i class="fas fa-tools"></i>
              </div>
              <div class="panel-label">
                <span>Admin</span>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
    
    <h2>UPCOMING EVENTS</h2>
      
    <div id="upcoming-events-container">
      <div id="upcoming-events-list-container">
        <ul id="upcoming-events-list">
          <li class="upcoming-events-list-item">
            <div class="date-section">
              <div class="month">SEPT</div>
              <div class="number">9</div>
              <div class="day-of-week">WED</div>
            </div>
            <div class="details">
              <div class="event-name">Convalescent Home Visit</div>
              <div class="event-time">10:00 AM - 12:00 PM</div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/admin/resources/index.html.erb
<div id="resources-index-page" class="page">
  <%= render "shared/site_header" %>
  
  <div class="page-content">
    <%= react_component("ClubResourcesPage", props: {authenticityToken: form_authenticity_token, resources: @resources}, prerender: false) %>
  </div>
</div>

app/views/layouts/admin.html.haml
!!! 5
%html{lang: I18n.locale}
  %head
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "text/html; charset=utf-8", "http-equiv" => "Content-Type"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport; charset=utf-8"}
    %meta{content: "NONE,NOARCHIVE", name: "robots"}
    = csrf_meta_tag
    = stylesheet_link_tag "rails_admin/rails_admin.css", media: :all
    = stylesheet_link_tag "custom_rails_admin.css", media: :all
    = javascript_include_tag "rails_admin/rails_admin.js"
    = javascript_pack_tag "application"
  %body.rails_admin
    #admin-js{:'data-i18n-options' => I18n.t("admin.js").to_json}
    -# Initialize JS simple i18n
    :javascript
      RailsAdmin.I18n.init('#{I18n.locale}', document.getElementById("admin-js").dataset.i18nOptions);
    #loading.label.label-warning{style: 'display:none; position:fixed; right:20px; bottom:20px; z-index:100000'}= t('admin.loading')
    %nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{ type: 'button', data: { toggle: 'collapse', target: '#secondary-navigation' } }
            %span.sr-only= t('admin.toggle_navigation')
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: rails_admin_path}
            = "Club Manager"
            %small= "UCSD Tzu Ching"
    .container-fluid
      .row
        .col-sm-3.col-md-2.sidebar-nav
          %ul.nav.nav-pills.nav-stacked
            %li.nav-header.dropdown-header Navigation
            %li= link_to 'Back to Manager', rails_admin_path
        .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2
          .row-fluid{style: 'padding-top:10px'}
            = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width">
  <title>Workspace</title>
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Lato|Oswald:300">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reimbursements/confirmation.html.erb
<div id="reimbursements-confirmation-page" class="page">
  <%= render "shared/site_header" %>
  
  <div class="message-box">
    We have recorded your reimbursement request. Thanks again for driving!
  </div>
</div>

app/views/reimbursements/reimbursement_already_exists.erb
<div id="reimbursements-already-exists-page" class="page">
  <%= render "shared/site_header" %>
  
  <div class="message-box">
    Oops! A reimbursement for you was already recorded for this event. 
  </div>
</div>

app/views/shared/_site_header.html.erb
<div id="site-header">
  <a href=<%= admin_root_path %>>
    <div id="site-header-content">
      <h1 id="site-title">UCSD TZU CHING</h1>
      <h2 id="site-subtitle">COMPASSIONATE YOUTH</h2>
    </div>
  </a>
</div>

<div id="site-navigation">
  
</div>